### PR TITLE
- add modCKEditor

### PR DESCRIPTION
**Pull request by vgrish**

### CODE REVIEW

**Comment by Kookabura** [comment]
That's a very good editor packaged in an interesting way. Every update delivers you the latest version of CKEditor. It might be a good substitution for the old good TinyMCE.

**Comment by Bruno17** [comment]
Thanks!
For which CKEditor - Extra is this for?

**Comment by Kookabura** [comment]
It's for modCKEditor extra. It's available at http://rstore.pro/extras/ repository.

**Comment by Bruno17** [comment]
feel free to reopen, if this project is still active and working

**Pull request closed without merging**
